// src/engine/actions.js

// Central registry of action type strings.
// These are what your UI will dispatch and what rules.js switches on.
export const ActionTypes = {
  // Global-ish
  START_TURN: 'START_TURN',
  END_TURN: 'END_TURN',

  // Home stage
  DRAW_HOME_CARD: 'DRAW_HOME_CARD',
  ATTEMPT_LEAVE_HOME: 'ATTEMPT_LEAVE_HOME',

  // Dreamer
  DRAW_SOCIAL_CARD: 'DRAW_SOCIAL_CARD',
  ROLL_TIME: 'ROLL_TIME',
  ATTEND_SOCIAL_EVENT: 'ATTEND_SOCIAL_EVENT',
  SKIP_SOCIAL_EVENT: 'SKIP_SOCIAL_EVENT',
  ATTEMPT_ADVANCE_DREAMER: 'ATTEMPT_ADVANCE_DREAMER',


  // Amateur
  CHOOSE_JOB: 'CHOOSE_JOB',
  GO_TO_WORK: 'GO_TO_WORK',
  TAKE_PROF_DEV: 'TAKE_PROF_DEV', // <- typo! see fix below
  START_MINOR_WORK: 'START_MINOR_WORK',
  PROGRESS_MINOR_WORK: 'PROGRESS_MINOR_WORK',
  COMPILE_PORTFOLIO: 'COMPILE_PORTFOLIO',
  ATTEMPT_ADVANCE_PRO: 'ATTEMPT_ADVANCE_PRO',

  // Pro
  WORK_ON_MASTERWORK: 'WORK_ON_MASTERWORK',
  DRAW_PRO_CARD: 'DRAW_PRO_CARD',
  RESOLVE_PRO_CARD_CHOICE: 'RESOLVE_PRO_CARD_CHOICE',
  PRO_MAINTENANCE_CHECK: 'PRO_MAINTENANCE_CHECK',

  // Culture
  DRAW_CULTURE_CARD: 'DRAW_CULTURE_CARD'
};
