// src/engine/actions.js

// Central registry of action type strings.
// These are what your UI will dispatch and what rules.js switches on.
export const ActionTypes = {
  // Global-ish
  START_TURN: 'START_TURN',
  END_TURN: 'END_TURN',
    // PR / Scandal (new)
  LAY_LOW: 'LAY_LOW',
  PLANT_HIT_PIECE: 'PLANT_HIT_PIECE',
  BUYOUT_SCANDAL: 'BUYOUT_SCANDAL',

    // Zeitgeist
  ZEITGEIST_CONVERT_INSPIRATION: 'ZEITGEIST_CONVERT_INSPIRATION',


  // Downtime (available on any stage as long as you have time)
  DOWNTIME_PRACTICE: 'DOWNTIME_PRACTICE',
  DOWNTIME_SLEEP: 'DOWNTIME_SLEEP',
  DOWNTIME_EAT_AT_HOME: 'DOWNTIME_EAT_AT_HOME',
  
  // Home stage
  DRAW_HOME_CARD: 'DRAW_HOME_CARD',
  ATTEMPT_LEAVE_HOME: 'ATTEMPT_LEAVE_HOME',

  // Dreamer
  CHOOSE_JOB: 'CHOOSE_JOB',
  QUIT_JOB: 'QUIT_JOB',
  GO_TO_WORK: 'GO_TO_WORK',
  DRAW_SOCIAL_CARD: 'DRAW_SOCIAL_CARD',
  ROLL_TIME: 'ROLL_TIME',
  ATTEND_SOCIAL_EVENT: 'ATTEND_SOCIAL_EVENT',
  SKIP_SOCIAL_EVENT: 'SKIP_SOCIAL_EVENT',
  ATTEMPT_ADVANCE_DREAMER: 'ATTEMPT_ADVANCE_DREAMER',

  // Amateur
  TAKE_PROF_DEV: 'TAKE_PROF_DEV',
  RESOLVE_PROF_DEV_CHOICE: 'RESOLVE_PROF_DEV_CHOICE',
  START_MINOR_WORK: 'START_MINOR_WORK',
  PROGRESS_MINOR_WORK: 'PROGRESS_MINOR_WORK',
  ATTEMPT_ADVANCE_PRO: 'ATTEMPT_ADVANCE_PRO',
  

  // Pro
  WORK_ON_MASTERWORK: 'WORK_ON_MASTERWORK',
  DRAW_PRO_CARD: 'DRAW_PRO_CARD',
  RESOLVE_PRO_CARD_CHOICE: 'RESOLVE_PRO_CARD_CHOICE',
  PRO_MAINTENANCE_CHECK: 'PRO_MAINTENANCE_CHECK',

  // Culture
  DRAW_CULTURE_CARD: 'DRAW_CULTURE_CARD'
};
